using System;
using System.IO;
using System.Text;

namespace WindowsOptimizer
{
    public static class SafeReclaimScriptBuilder
    {
        public static string BuildScript()
        {
            var sb = new StringBuilder();
            sb.AppendLine("<#");
            sb.AppendLine(".SYNOPSIS");
            sb.AppendLine("  Deterministic, non-destructive C: drive reclaim script.");
            sb.AppendLine();
            sb.AppendLine(".DESCRIPTION");
            sb.AppendLine("  - Measures C: free space before/after.");
            sb.AppendLine("  - Cleans temp and cache locations that are generally safe to delete.");
            sb.AppendLine("  - Clears Windows Update download cache and Delivery Optimization cache.");
            sb.AppendLine("  - Optionally runs DISM component store cleanup with /ResetBase.");
            sb.AppendLine("  - Logs all actions and outcomes.");
            sb.AppendLine();
            sb.AppendLine(".NOTES");
            sb.AppendLine("  Run in elevated PowerShell (Run as Administrator).");
            sb.AppendLine("#>");
            sb.AppendLine();
            sb.AppendLine("#--------------------------- CONFIG ---------------------------#");
            sb.AppendLine("$DriveLetter      = 'C'");
            sb.AppendLine("$LogRoot          = 'C:\\Temp'");
            sb.AppendLine("$Timestamp        = Get-Date -Format 'yyyyMMdd_HHmmss'");
            sb.AppendLine("$LogFile          = Join-Path $LogRoot \"Reclaim_${DriveLetter}_$Timestamp.log\"");
            sb.AppendLine("$RunDismCleanup   = $true");
            sb.AppendLine();
            sb.AppendLine("$CleanupPaths = @(");
            sb.AppendLine("    \"$env:TEMP\",");
            sb.AppendLine("    'C:\\Windows\\Temp',");
            sb.AppendLine("    \"$env:USERPROFILE\\AppData\\Local\\Temp\",");
            sb.AppendLine("    'C:\\Windows\\SoftwareDistribution\\Download',");
            sb.AppendLine("    'C:\\Windows\\DeliveryOptimization',");
            sb.AppendLine("    'C:\\Windows\\Logs\\CBS',");
            sb.AppendLine("    \"$env:LOCALAPPDATA\\Microsoft\\Windows\\INetCache\",");
            sb.AppendLine("    \"$env:LOCALAPPDATA\\Microsoft\\Edge\\User Data\\Default\\Cache\",");
            sb.AppendLine("    \"$env:LOCALAPPDATA\\Google\\Chrome\\User Data\\Default\\Cache\",");
            sb.AppendLine("    \"$env:APPDATA\\Mozilla\\Firefox\\Profiles\\*\\cache2\"");
            sb.AppendLine(")");
            sb.AppendLine();
            sb.AppendLine("#--------------------------- HELPERS ---------------------------#");
            sb.AppendLine("function Ensure-LogRoot {");
            sb.AppendLine("    if (-not (Test-Path $LogRoot)) {");
            sb.AppendLine("        New-Item -Path $LogRoot -ItemType Directory -Force | Out-Null");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("function Write-Log {");
            sb.AppendLine("    param([string]$Message)");
            sb.AppendLine("    $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'");
            sb.AppendLine("    $line  = \"[$stamp] $Message\"");
            sb.AppendLine("    Write-Host $line");
            sb.AppendLine("    Add-Content -Path $LogFile -Value $line");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("function Get-FreeSpaceGB {");
            sb.AppendLine("    param([string]$Drive = 'C')");
            sb.AppendLine("    $drive = Get-PSDrive -Name $Drive -ErrorAction Stop");
            sb.AppendLine("    [math]::Round($drive.Free / 1GB, 2)");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("function SafeDelete {");
            sb.AppendLine("    param([string]$Path)");
            sb.AppendLine("    $targets = Get-Item -LiteralPath $Path -ErrorAction SilentlyContinue");
            sb.AppendLine("    if (-not $targets) {");
            sb.AppendLine("        $targets = Get-ChildItem -Path $Path -ErrorAction SilentlyContinue");
            sb.AppendLine("    }");
            sb.AppendLine("    if (-not $targets) {");
            sb.AppendLine("        Write-Log \"Skip (not found): $Path\"");
            sb.AppendLine("        return");
            sb.AppendLine("    }");
            sb.AppendLine("    foreach ($t in $targets) {");
            sb.AppendLine("        try {");
            sb.AppendLine("            Remove-Item -Path $t.FullName -Recurse -Force -ErrorAction Stop");
            sb.AppendLine("            Write-Log \"Deleted: $($t.FullName)\"");
            sb.AppendLine("        }");
            sb.AppendLine("        catch {");
            sb.AppendLine("            Write-Log \"Skipped (locked or denied): $($t.FullName) - $($_.Exception.Message)\"");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("#--------------------------- MAIN ---------------------------#");
            sb.AppendLine("if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {");
            sb.AppendLine("    Write-Host 'Please run this script in an elevated PowerShell session (Run as Administrator).' -ForegroundColor Red");
            sb.AppendLine("    exit 1");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("Ensure-LogRoot");
            sb.AppendLine("Write-Log '=== Reclaim C: Script Started ==='");
            sb.AppendLine("Write-Log \"Log file: $LogFile\"");
            sb.AppendLine();
            sb.AppendLine("$freeBefore = Get-FreeSpaceGB -Drive $DriveLetter");
            sb.AppendLine("Write-Log \"Free space on $DriveLetter: before cleanup = $freeBefore GB\"");
            sb.AppendLine();
            sb.AppendLine("try {");
            sb.AppendLine("    Write-Log 'Clearing Recycle Bin...'");
            sb.AppendLine("    Clear-RecycleBin -Force -ErrorAction SilentlyContinue");
            sb.AppendLine("}");
            sb.AppendLine("catch {");
            sb.AppendLine("    Write-Log \"Recycle Bin clear skipped: $($_.Exception.Message)\"");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("Write-Log 'Stopping Windows Update related services...'");
            sb.AppendLine("$servicesToStop = @('wuauserv','bits')");
            sb.AppendLine("foreach ($svc in $servicesToStop) {");
            sb.AppendLine("    try {");
            sb.AppendLine("        Stop-Service -Name $svc -Force -ErrorAction SilentlyContinue");
            sb.AppendLine("        Write-Log \"Stopped service: $svc\"");
            sb.AppendLine("    }");
            sb.AppendLine("    catch {");
            sb.AppendLine("        Write-Log \"Could not stop service $svc: $($_.Exception.Message)\"");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("Write-Log 'Cleaning safe temp and cache locations...'");
            sb.AppendLine("foreach ($path in $CleanupPaths) {");
            sb.AppendLine("    Write-Log \"Processing: $path\"");
            sb.AppendLine("    SafeDelete -Path $path");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("Write-Log 'Restarting Windows Update related services...'");
            sb.AppendLine("foreach ($svc in $servicesToStop) {");
            sb.AppendLine("    try {");
            sb.AppendLine("        Start-Service -Name $svc -ErrorAction SilentlyContinue");
            sb.AppendLine("        Write-Log \"Started service: $svc\"");
            sb.AppendLine("    }");
            sb.AppendLine("    catch {");
            sb.AppendLine("        Write-Log \"Could not start service $svc: $($_.Exception.Message)\"");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("if ($RunDismCleanup) {");
            sb.AppendLine("    Write-Log 'DISM component store cleanup is enabled.'");
            sb.AppendLine("    $answer = Read-Host \"Run 'Dism.exe /Online /Cleanup-Image /StartComponentCleanup /ResetBase'? This is irreversible but Microsoft-supported. (Y/N)\"");
            sb.AppendLine("    if ($answer -match '^[Yy]') {");
            sb.AppendLine("        Write-Log 'Starting DISM component store cleanup...'");
            sb.AppendLine("        try {");
            sb.AppendLine("            Start-Process -FilePath 'Dism.exe' -ArgumentList '/Online','/Cleanup-Image','/StartComponentCleanup','/ResetBase' -Wait -WindowStyle Hidden");
            sb.AppendLine("            Write-Log 'DISM component store cleanup completed.'");
            sb.AppendLine("        }");
            sb.AppendLine("        catch {");
            sb.AppendLine("            Write-Log \"DISM cleanup failed: $($_.Exception.Message)\"");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("    else {");
            sb.AppendLine("        Write-Log 'DISM component store cleanup skipped by user.'");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("else {");
            sb.AppendLine("    Write-Log 'DISM component store cleanup disabled by configuration.'");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("$freeAfter = Get-FreeSpaceGB -Drive $DriveLetter");
            sb.AppendLine("$delta = [math]::Round(($freeAfter - $freeBefore), 2)");
            sb.AppendLine("Write-Log \"Free space on $DriveLetter: after cleanup = $freeAfter GB\"");
            sb.AppendLine("Write-Log \"Net change: $delta GB\"");
            sb.AppendLine("Write-Log '=== Reclaim C: Script Completed ==='");
            sb.AppendLine();
            sb.AppendLine("Write-Host ''");
            sb.AppendLine("Write-Host \"Reclaim complete. Before: $freeBefore GB, After: $freeAfter GB, Delta: $delta GB\" -ForegroundColor Cyan");
            sb.AppendLine("Write-Host \"Details logged to: $LogFile\"");
            return sb.ToString();
        }

        public static string Export(string outputDirectory)
        {
            if (string.IsNullOrWhiteSpace(outputDirectory))
                throw new ArgumentException("Output directory is required.", nameof(outputDirectory));

            Directory.CreateDirectory(outputDirectory);
            string path = Path.Combine(outputDirectory, "Reclaim-C-Safe.ps1");
            File.WriteAllText(path, BuildScript(), new UTF8Encoding(false));
            return path;
        }
    }
}
